### ISSUE TITLE
Options fail to load

### ISSUE THREAD

**Issue by Trylinski** [mack94/urban-traffic-monitoring-application#13]
When starting charts application there is a warning messeage: 
paź 23, 2016 12:48:52 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

The program doesnt load preferences. It happened on 2 different computers.

**Comment by mack94** [comment]
http://stackoverflow.com/questions/16428098/groovy-shell-warning-could-not-open-create-prefs-root-node

**Comment by mack94** [comment]
It is said to be Java bug which status is "won't fix"
"http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6790382"

In my opinion, need to be mentioned in user guide int the '_bugs and possible troubles_' section.

**Comment by Trylinski** [comment]
After adding key to the registry according to instructions warning doesnt show but options still dont load.

**Comment by mack94** [comment]
Options already loaded. 
The _initialize_ method in Charts was missing.
